name: Hello Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # å¯ä»¥æ‰‹åŠ¨è§¦å‘

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: æ‰“å°ä¿¡æ¯
        run: echo "ğŸ‰ ä½ å¥½ GitHub Actions!"
